### PR TITLE
Add support for Java 8 constants

### PR DESCRIPTION
**Pull request by jcestibariz**
Created from patch provided by @iloveeclipse, but only with significant
changes.

### CODE REVIEW

**Comment by scstarkey** [comment]
Great that this is merged!

How does the new artifact get into Maven Central? Should the issue also be closed?

**Comment by davidburkhart** [comment]
It seems that it is not clear, who is maintaining the maven artifact, as it is not the author of jdepend. I would appreciate it too if somebody could create a release on maven central. 
Btw. the version number in build.xml would have to be adjusted before.

**Comment by BenRomberg** [comment]
Btw, there's a fork from @nidi3 available on Maven Central that includes various fixes: https://github.com/nidi3/jdepend
```
    <dependency>
      <groupId>guru.nidi</groupId>
      <artifactId>jdepend</artifactId>
      <version>2.9.5</version>
    </dependency>
```

**Comment by nickgrealy** [comment]
Any progress on a new release?

**Comment by davidburkhart** [comment]
use the force / fork ;)

**Pull request merged**
